#!/bin/bash

#### This little script copies over the geoserver data directory
#### from the repository if it doesn't already exist
# source: https://github.com/thesteve0/geoserver-on-openshift

if ! [ -d "$OPENSHIFT_DATA_DIR/geoserver_data"  ]; then
  mv $OPENSHIFT_REPO_DIR/webapps/ROOT/data/ $OPENSHIFT_DATA_DIR/geoserver_data/
fi

