#!/bin/bash

touch "$OPENSHIFT_DATA_DIR/deploy.dummy"

#### This little script copies over the geoserver data directory
#### from the repository if it doesn't already exist
# source: https://github.com/thesteve0/geoserver-on-openshift

if ! [ -d "$OPENSHIFT_DATA_DIR/geoserver_data"  ]; then
  cp --recursive $OPENSHIFT_REPO_DIR/webapps/geoserver/data/ $OPENSHIFT_DATA_DIR/geoserver_data/
fi

